spring:
  profiles:
    include: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # Required
            client-secret: # Required
            scope: email, profile
  data:
    redis:
      host: localhost
      password:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: none
        secure: true
        max-age: 3600
custom:
  host:
    client: http://localhost:3000
